### ISSUE TITLE
Aquarius java SDK give exception on append points to ts

### ISSUE THREAD

**Issue by IdeamDesa** [AquaticInformatics/aquarius-sdk-java#66]
Greetings, 
First, thankyou for all support.
I trying to append points to a timeseries throught java SDK, but have problemns with the append operation, ... and i dont now why......

Also try to update (overwriteappend) the points, the extrange is that the overwriteappend operation works fine...

This is the code:

try (AquariusClient cliente= AquariusClient.createConnectedClient(AQUARIUS_PATH, AQUARIUS_USER, AQUARIUS_PASSWORD)) {
            String uniqueId = timeSeriesQuerier.obtenerTimeSeriesUniqueId(serie.getEtiqueta(), serie.getEstacion());
            ArrayList<TimeSeriesPoint> tspoints = new ArrayList<>();            
            for (PuntoSerieDeTiempo puntoSdT : serie.getListaPuntos()) {
                TimeSeriesPoint puntots=new TimeSeriesPoint();
                puntots.setTime(puntoSdT.getTimestamp().toInstant());
                puntots.setValue(puntoSdT.getDato());
                tspoints.add(puntots);
            }
            PostTimeSeriesAppend append=new PostTimeSeriesAppend();
            append.setPoints(tspoints);
            append.setUniqueId(uniqueId);
            AppendResponse appendResponse = cliente.Acquisition.post(append);                                
        }catch (WebServiceException e) {
            System.out.println("mensaje:"+e.getErrorMessage()+" code:"+e.getErrorCode());
//            e.printStackTrace();
            throw e;            
        } catch (Exception ex) {
            throw ex;            
        }

I set a breakpoint in the exception (that dont show any message) and i see that in the response body says "You dont have permission to view this directory or page", its a privileges problem? how i must configure the conection user for that works?

![image](https://user-images.githubusercontent.com/39776547/42469131-723ccf88-837c-11e8-9da0-09db1e1324bf.png)

**Comment by DougSchmidt-AI** [comment]
That is definitely an odd/unexpected response.

The fact that the WebServiceException.ResponseBody field is the plain text string `"You do not have permission to view this directory or page."` instead of a JSON stream makes me think that this response is coming from the web server hosting your AQTS server.

When the AQUARIUS application responds with an API error, the response body will always be a JSON document of some sort.

Here's what IntelliJ shows me when I use the wrong credentials. You can see that the ResponseBody field a JSON document, not a plain text string:

![image](https://user-images.githubusercontent.com/54773/42536754-c9e53696-8447-11e8-93ab-36ac0ef9dc62.png)

**Comment by DougSchmidt-AI** [comment]
Oh, I see the problem. You have supplied the wrong user credentials. Either your username or password is incorrect.

I found a set of AQTS credentials in one of your public GitHub repos (you probably should change those credentials, since they are now visible to everyone on the internet for a month).

When I changed my test example to point to your server, with incorrect credentials, I get the same error that you've seen:
![image](https://user-images.githubusercontent.com/54773/42537394-96ee9578-8449-11e8-8c56-dd2c3b4cbcac.png)

I used the [Wiki guidance for capturing Java HTTP requests using Fiddler](https://github.com/AquaticInformatics/aquarius-sdk-java/wiki/Capture-your-HTTP-traffic) and saw that when a Java authentication request fails, it looks like the [ServiceStack.Java](https://github.com/ServiceStack/ServiceStack.Java) client frame (used by our Java platform SDK) tries some more authentication fallback logic, sending two more POST requests.

![image](https://user-images.githubusercontent.com/54773/42537667-66c73f70-844a-11e8-9641-c04c1f01f6ef.png)

The exception your code is getting is the response of the 3rd POST failure.

So if you use the correct credentials, your append request should start working.
