### ISSUE TITLE
Delete time series points with SDK

### ISSUE THREAD

**Issue by IdeamDesa** [AquaticInformatics/aquarius-sdk-java#72]
Greetings,

I trying to delete a point in a series (en the corrected series), and am looking in SDK, methods for that specific purpose, i dont wanna delete all series because is already a working series with corrected data by thematic user (hydrologist), there a way to do this not manually? 
I´m looking for one method for that a i have many series with many points that were saved with a wrong hour and after were saved with right hour then have all the points but at least 1240 points duplicated with wrong hour and i cannot request to the hydrologist for delete that points with the aquarius data corrector tool

**Comment by DougSchmidt-AI** [comment]
There is a way you can achieve what you need using what is called an "overwrite append" request. "Overwrite appends" are intended for exactly this purpose, to perform a one-time fix of an operator error.

- Overwrite append operations should not be performed frequently on a single time-series, since the read performance of that time-series will begin to degrade after roughly a few hundred overwrite operations. Doing this a few thousand times on a single time-series will really impact your system performance in a negative way.
- Keep in mind this restriction is **per time-series**. It is completely fine to make one overwrite append to ten thousand different time-series. But if you make ten-thousand overwrite appends to the same time-series, that single time-series will become slower and slower to retrieve.
- If you find that you need to fix the same time-series repeatedly, you should consider using a reflected time-series to store the data, since a reflected time-series is designed to perform well in this very use-case.
- The situation you are describing (1240 total points to delete across many different time-series) sounds fine to me to use the "overwrite append" approach.

The important part is to specify a time-range which only includes the single time to delete. The `TimeRange.Start` property should be time to delete, and the `TimeRange.End` property should be exactly 100 nanoseconds later (0.0000001 seconds, 6 zeros followed by a 1).

This tiny time-range is used because the resolution of all time-series within AQTS is exactly 100 nanoseconds.

This snippet below is based off the [Appending points to basic time-series](https://github.com/AquaticInformatics/aquarius-sdk-java/wiki/Appending-points-to-a-basic-time-series) wiki page example, with five changes:
- The `appendPoints()` method is renamed to `deleteSinglePoint()`
- An extra `Instant timeToDelete` parameter is added to `deleteSinglePoint()`
- A `timeRange` Interval variable is created to represent exactly the one point to delete
- The `PostTimeSeriesOverwriteAppend` request DTO is used, instead of the `PostTimeSeriesAppend` request DTO
- No new points are added to append request. This will cause AQTS to just delete all existing points within the `TimeRange` request property.

```java
public void deleteOnePoint(String timeSeriesIdentifier, Instant timeToDelete) throws InterruptedException {
	String uniqueId = getTimeSeriesUniqueId(timeSeriesIdentifier);

	Interval timeRange = new Interval();
	timeRange.Start = timeToDelete;
	timeRange.End = timeToDelete.plusNanos(100);

	AppendResponse appendResponse = _client.Acquisition.post(new PostTimeSeriesOverwriteAppend()
			.setUniqueId(uniqueId)
			.setTimeRange(timeRange));

	Instant pollStart = Instant.now();
	TimeSeriesAppendStatus pollResponse = pollUntilComplete(appendResponse.AppendRequestIdentifier);

	Duration elapsed = Duration.between(pollStart, Instant.now());

	System.out.format("Appended %d points (deleting %d points) in %s\n", pollResponse.NumberOfPointsAppended, pollResponse.NumberOfPointsDeleted, elapsed.toString());
}
```

**Comment by IdeamDesa** [comment]
I´m worried, sorry i meant at least 1240 points per series, for many locations, the structure of the points is that you can see in the image, starts about 2017 and finalize early in 2018, as say 1240 points per series, and series have 9000 points aprox, the complex is that the hydrologist already correct some values in this dates, for delete this 1240 points i must excute PostTimeSeriesOverwriteAppend() 1240 times? that degrade series performance? what you recomend me?

![image](https://user-images.githubusercontent.com/39776547/43668526-0cea326c-9743-11e8-839e-d733c1fd3435.png)
