### ISSUE TITLE
Create Derived TimeSeries Programmatically

### ISSUE THREAD

**Issue by IdeamDesa** [AquaticInformatics/aquarius-sdk-java#73]
Greetings, 
In this moment i'm need create many derived time series for diferent locations, around 8000 derived series, there are a programmatically method for do this, using the sdk or rest api ?

Thnks for the help!

**Comment by DougSchmidt-AI** [comment]
Yes, the Provisioning API can be used to create derived time-series.

Please note: Only perform these actions on your test server until your code is debugged. Don't start creating new time-series on a system in production, since you can make mistakes which impact other operation.

And when you get it wrong in your test environment (Don't worry, everybody gets it wrong the first few times until their code is debugged), you'll want to use the free [LocationDeleter.exe tool](https://github.com/AquaticInformatics/examples/blob/master/TimeSeries/PublicApis/SdkExamples/LocationDeleter/Readme.md#deleting-time-series) to delete the badly create time-series and start over.

There are 4 different API operations which can be used to create a time-series. The code is very similar to the [wiki example for creating a basic time-series](https://github.com/AquaticInformatics/aquarius-sdk-java/wiki/Creating-a-time-series). Just substitute the correct classname for `PostBasicTimeSeries`.

| Provisioning API Operation | SDK Class |
| --- | --- |
| `POST /locations/{LocationUniqueId}/timeseries/basic` | `PostBasicTimeSeries` |
| `POST /locations/{LocationUniqueId}/timeseries/reflected` | `PostReflectedTimeSeries` |
| `POST /locations/{LocationUniqueId}/timeseries/calculated` | `PostCalculatedDerivedTimeSeries` |
| `POST /locations/{LocationUniqueId}/timeseries/statistical` | `PostStatisticalDerivedTimeSeries` |

On your test app server, try it out on the Swagger-UI page first:
- Log into AQUARIUS as you normally would. Your authenticated session will be used in subsequent requests made from the Swagger UI page.
- Browse to the `/AQUARIUS/Provisioning/v1` endpoint
- Click the  and click the "Swagger UI" link at the top of the page.
- Browse to the `/locations` route and expand the API operation you want to try
- Enter your values and click the "Try it out!" button to test the API

**Comment by IdeamDesa** [comment]
Thank you so much Doug!!!!!
